name = "identity"
main = "index.ts"
compatibility_date = "2023-08-01"
minify = true
workers_dev = false

routes = [
    { pattern = "identity.coverbase.co", custom_domain = true, zone_id = "bedfb75536606b29b5266fefc8c6e343" }
]

[dev]
port = 5000